name: bookie

static_sites:
  - name: app
    environment_slug: gatsby
    github:
      repo: neurologists/bookie
      branch: master
      deploy_on_push: true
    source_dir: packages/app
    build_command: npm run build

workers:
  - name: updater
    environment_slug: python
    github:
      branch: main
      deploy_on_push: true
      repo: neurologists/bookie
    run_command: python main.py
